## [v0.3.6](https://pypi.org/project/amsdal_cli/0.3.6/) - 2024-12-16


### Fixed

- Fixed sync-db auth error (sync-db-auth-error)
